#!/bin/sh
COMMIT_MSG_FILE=$1
BRANCH_NAME=$(git branch | grep ^* | sed 's/\* //g')
_regexp="(fix|feat)"

/usr/bin/perl -i.bak -ne 'print unless(m/^. Please enter the commit message/..m/^#$/)' "$COMMIT_MSG_FILE"

if [[ $BRANCH_NAME =~ $_regexp ]]
then
    _name="${BASH_REMATCH[1]}"

    _message=`cat $1`

    if [[ $_message == $_name* ]]
        then
        exit
    fi
    echo "$_name: $_message"
fi

